application: zshiftedz
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.css)
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.png)
  static_files: images/\1
  upload: images/(.*\.png)

- url: /.*
  script: version3.app

libraries:
- name: webapp2
  version: "2.5.1"
